{{- if not .Values.global.omitSidecarInjectorConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: sidecar-injector
    istio: sidecar-injector
data:
  values: |-
    {{ .Values.sidecarInjectorWebhook | toJson }}

  config: |-
    # Deprecated: user may install or not the autoinjector.
    policy: {{ .Values.global.proxy.autoInject }}
    template: |-
{{ .Files.Get "files/injection-template.yaml" | indent 6 }}
{{- end }}
