prometheus:
  # Controls the default scrape interval used in the ServiceMonitors
  scrapeInterval: 15s

  # Enabling this option will generate a Prometheus resource, causing the operator
  # to create a prometheus deployment according to the generated spec. It will also
  # create a service definition, destination rules, cluster roles and bindings, and
  # a service account. Only use this option if you have not already created and configured
  # a prometheus resource and/or you desire a distinct prometheus resource for Istio.
  createPrometheusResource: false

  # Enabling this will generate a ServiceMonitor to monitor Kubelet cAdvisor.
  createKubeletMonitor: true

  hub: docker.io/prom
  tag: v2.8.0
  retention: 6h

  service:
    annotations: {}
    nodePort:
      enabled: false
      port: 32090
