{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-galley
  namespace: {{ .Release.Namespace }}
  labels:
    app: galley
    release: {{ .Release.Name }}
    istio: galley
spec:
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
{{- if .Values.global.defaultPodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.global.defaultPodDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      app: galley
      release: {{ .Release.Name }}
      istio: galley
{{- end }}
