{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
{{- if $gateway.sds.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-egressgateway-sds
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
{{- end }}
