grafana:
  enabled: true
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: 6.0.2
  persist: false
  storageClassName: ""
  accessMode: ReadWriteMany
  security:
    enabled: false
    secretName: grafana
    usernameKey: username
    passphraseKey: passphrase

  contextPath: /grafana
  service:
    annotations: {}
    name: http
    type: ClusterIP
    externalPort: 3000
    loadBalancerIP:
    loadBalancerSourceRanges:

  ingress:
    enabled: false
    ## Used to create an Ingress record.
    hosts:
      - grafana.local
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    tls:
      # Secrets must be manually created in the namespace.
      # - secretName: grafana-tls
      #   hosts:
      #     - grafana.local

  # Optional: prometheus may be deployed in a different namespace
  # prometheusNamespace: istio-telemetry

  # Additional datasources. Prometheus included in the config map.
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      # - name: Prometheus2
      #   type: prometheus2
      #   orgId: 2
      #   url: http://prometheus:9090
      #   access: proxy
      #   isDefault: false
      #   jsonData:
      #     timeInterval: 5s
      #   editable: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'istio'
          orgId: 1
          folder: 'istio'
          type: file
          disableDeletion: false
          options:
            path: /var/lib/grafana/dashboards/istio

