# This file overrides values for e2e testing.

global:
  istioNamespace: istio-system
  configNamespace: istio-system
  telemetryNamespace: istio-system
  prometheusNamespace: istio-system
  policyNamespace: istio-system

  proxy:
    concurrency: 0
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

    accessLogFile: "/dev/stdout"
    enableCoreDump: true

  disablePolicyChecks: false
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

prometheus:
  scrapeInterval: 5s

gateways:
  istio-ingressgateway:
    autoscaleMax: 1
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Manually specify ports so we can have fixed node port
    # ports:
    # - port: 15020
    #   targetPort: 15020
    #   name: status-port
    # - port: 80
    #   targetPort: 80
    #   name: http2
    #   nodePort: 31380
    # - port: 443
    #   name: https
    # - port: 15029
    #   targetPort: 15029
    #   name: kiali
    # - port: 15030
    #   targetPort: 15030
    #   name: prometheus
    # - port: 15031
    #   targetPort: 15031
    #   name: grafana
    # - port: 15032
    #   targetPort: 15032
    #   name: tracing
    #   # This is the port where sni routing happens
    # - port: 15443
    #   targetPort: 15443
    #   name: tls

  istio-egressgateway:
    enabled: true
    autoscaleMax: 1
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi

mixer:
  policy:
    enabled: true
    replicaCount: 2
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  telemetry:
    enabled: true
    loadshedding:
      mode: disabled
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  adapters:
    stdio:
      enabled: true
  kiali:
    enabled: true

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true
  enableNamespacesByDefault: true

